// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOjLqt35PEMv2iO8GKi5U5ajz8iRgF5X8',
    appId: '1:559805853224:web:7560d07a0ecfe0b0a80f1d',
    messagingSenderId: '559805853224',
    projectId: 'ipsitasoft-tracker',
    authDomain: 'ipsitasoft-tracker.firebaseapp.com',
    storageBucket: 'ipsitasoft-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbfeTH71pSoaXJOplKwGWfsbGz8UdO96Y',
    appId: '1:559805853224:android:8317a56e718297d2a80f1d',
    messagingSenderId: '559805853224',
    projectId: 'ipsitasoft-tracker',
    storageBucket: 'ipsitasoft-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPhNMidKY6213iZZTOYKRbcdSjvebKKv0',
    appId: '1:559805853224:ios:8fdfc24625043f15a80f1d',
    messagingSenderId: '559805853224',
    projectId: 'ipsitasoft-tracker',
    storageBucket: 'ipsitasoft-tracker.appspot.com',
    iosClientId: '559805853224-4ds5m8930rvvqqs4ug7r15oj6mr41iqe.apps.googleusercontent.com',
    iosBundleId: 'com.ipsitasoft.trackerAdmin',
  );
}
